//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralTools.DataGrid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataGridResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataGridResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneralTools.DataGrid.DataGridResources", typeof(DataGridResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BooleanOff {
            get {
                object obj = ResourceManager.GetObject("BooleanOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BooleanOn {
            get {
                object obj = ResourceManager.GetObject("BooleanOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI CSS Framework 1.8.17
        /// *
        /// * Copyright 2011, AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * http://docs.jquery.com/UI/Theming/API
        /// */
        ///
        ////* Layout helpers
        ///----------------------------------*/
        ///.ui-helper-hidden { display: none; }
        ///.ui-helper-hidden-accessible { position: absolute !important; clip: rect(1px 1px 1px 1px); clip: rect(1px,1px,1px,1px); }
        ///.ui-helper-reset { margin: 0; padding: 0; border: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string darkHive {
            get {
                return ResourceManager.GetString("darkHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; (function ($) {
        ///	/**
        ///	 * jqGrid English Translation
        ///	 * Tony Tomov tony@trirand.com
        ///	 * http://trirand.com/blog/ 
        ///	 * Dual licensed under the MIT and GPL licenses:
        ///	 * http://www.opensource.org/licenses/mit-license.php
        ///	 * http://www.gnu.org/licenses/gpl.html
        ///	**/
        ///	$.jgrid = $.jgrid || {};
        ///	$.extend($.jgrid, {
        ///		defaults: {
        ///			recordtext: &quot;View {0} - {1} of {2}&quot;,
        ///			emptyrecords: &quot;No records to view&quot;,
        ///			loadtext: &quot;Loading...&quot;,
        ///			pgtext: &quot;Page {0} of {1}&quot;
        ///		},
        ///		search: {
        ///			caption: &quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel {
            get {
                object obj = ResourceManager.GetObject("Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; (function ($) {
        ///	/**
        ///	 * jqGrid Persian Translation
        ///	 * Dual licensed under the MIT and GPL licenses:
        ///	 * http://www.opensource.org/licenses/mit-license.php
        ///	 * http://www.gnu.org/licenses/gpl.html
        ///	**/
        ///	$.jgrid = $.jgrid || {};
        ///	$.extend($.jgrid, {
        ///		defaults: {
        ///			recordtext: &quot;نمابش {0} - {1} از {2}&quot;,
        ///			emptyrecords: &quot;رکوردی یافت نشد&quot;,
        ///			loadtext: &quot;بارگزاري...&quot;,
        ///			pgtext: &quot;صفحه {0} از {1}&quot;
        ///		},
        ///		search: {
        ///			caption: &quot;جستجو...&quot;,
        ///			Find: &quot;يافته ها&quot;,
        ///			Reset: &quot;از نو&quot;,
        ///			odata: [{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.js.
        /// </summary>
        internal static string JavaScript_En {
            get {
                return ResourceManager.GetString("JavaScript_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa.js.
        /// </summary>
        internal static string JavaScript_Fa {
            get {
                return ResourceManager.GetString("JavaScript_Fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jqueryGrid.min.js.
        /// </summary>
        internal static string JavaScript_JqueryGrid {
            get {
                return ResourceManager.GetString("JavaScript_JqueryGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jqueryGrid.min.js.
        /// </summary>
        internal static string JavaScript_jqueryGridMin {
            get {
                return ResourceManager.GetString("JavaScript_jqueryGridMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jqueryGrid.js.
        /// </summary>
        internal static string JavaScript_jqueryGridSrc {
            get {
                return ResourceManager.GetString("JavaScript_jqueryGridSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jqueryJson_min.js.
        /// </summary>
        internal static string JavaScript_JqueryJson {
            get {
                return ResourceManager.GetString("JavaScript_JqueryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        ///*
        ///* @license Guriddo jqGrid JS - v4.8.2 - 2015-03-24
        ///* Copyright(c) 2008, Tony Tomov, tony@trirand.com
        ///* 
        ///* License: http://guriddo.net/?page_id=103334
        ///*/
        ///(function (factory) {
        ///	&quot;use strict&quot;;
        ///	if (typeof define === &quot;function&quot; &amp;&amp; define.amd) {
        ///		// AMD. Register as an anonymous module.
        ///		define([
        ///			&quot;jquery&quot;
        ///		], factory);
        ///	} else {
        ///		// Browser globals
        ///		factory(jQuery);
        ///	}
        ///}(function ($) {
        ///	&quot;use strict&quot;;
        ///	//module begin
        ///	$.jgrid = $.jgrid || {};
        ///	if (!$.jgrid.hasOwnProperty(&quot;defau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jqueryGrid {
            get {
                return ResourceManager.GetString("jqueryGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        ///*
        ///* @license Guriddo jqGrid JS - v4.8.2 - 2015-03-24
        ///* Copyright(c) 2008, Tony Tomov, tony@trirand.com
        ///* 
        ///* License: http://guriddo.net/?page_id=103334
        ///*/
        ///(function(n){&quot;use strict&quot;;typeof define==&quot;function&quot;&amp;&amp;define.amd?define([&quot;jquery&quot;],n):n(jQuery)})(function($){&quot;use strict&quot;;function k(n,t){var i,r,u=[],f;if(!this||typeof n!=&quot;function&quot;||n instanceof RegExp)throw new TypeError;for(f=this.length,i=0;i&lt;f;i++)if(this.hasOwnProperty(i)&amp;&amp;(r=this[i],n.call(t,r,i,this))){u.push(r);break}return u}var n,v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jqueryGrid_min {
            get {
                return ResourceManager.GetString("jqueryGrid.min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI CSS Framework 1.8.17
        /// *
        /// * Copyright 2011, AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * http://docs.jquery.com/UI/Theming/API
        /// */
        ///
        ////* Layout helpers
        ///----------------------------------*/
        ///.ui-helper-hidden { display: none; }
        ///.ui-helper-hidden-accessible { position: absolute !important; clip: rect(1px 1px 1px 1px); clip: rect(1px,1px,1px,1px); }
        ///.ui-helper-reset { margin: 0; padding: 0; border: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lightness {
            get {
                return ResourceManager.GetString("lightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pdf {
            get {
                object obj = ResourceManager.GetObject("Pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* jQuery UI CSS Framework
        ///* Copyright (c) 2010 AUTHORS.txt (http://jqueryui.com/about)
        ///* Dual licensed under the MIT (MIT-LICENSE.txt) and GPL (GPL-LICENSE.txt) licenses.
        ///*/
        ///
        ////* Layout helpers
        ///----------------------------------*/
        ///.ui-helper-hidden { display: none; }
        ///.ui-helper-hidden-accessible { position: absolute; left: -99999999px; }
        ///.ui-helper-reset { margin: 0; padding: 0; border: 0; outline: 0; line-height: 1.3; text-decoration: none; font-size: 100%; list-style: none; }
        ///.ui-helper-clear [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string redmond {
            get {
                return ResourceManager.GetString("redmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uiGrid.css.
        /// </summary>
        internal static string Style_UiGrid {
            get {
                return ResourceManager.GetString("Style_UiGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darkHive.darkHive.css.
        /// </summary>
        internal static string Themes_DarkHive {
            get {
                return ResourceManager.GetString("Themes_DarkHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lightness.lightness.css.
        /// </summary>
        internal static string Themes_Lightness {
            get {
                return ResourceManager.GetString("Themes_Lightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redmond.redmond.css.
        /// </summary>
        internal static string Themes_Redmond {
            get {
                return ResourceManager.GetString("Themes_Redmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_anim_basic_16x16 {
            get {
                object obj = ResourceManager.GetObject("ui_anim_basic_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_diagonals_thick_18_b81900_40x40 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_diagonals_thick_18_b81900_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_diagonals_thick_20_666666_40x40 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_diagonals_thick_20_666666_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_flat_0_aaaaaa_40x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_0_aaaaaa_40x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_flat_10_000000_40x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_10_000000_40x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_flat_30_cccccc_40x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_30_cccccc_40x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_flat_50_5c5c5c_40x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_50_5c5c5c_40x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_flat_55_fbec88_40x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_55_fbec88_40x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_glass_100_f6f6f6_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_100_f6f6f6_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_glass_100_fdf5ce_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_100_fdf5ce_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_glass_40_ffc73d_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_40_ffc73d_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_glass_65_ffffff_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_65_ffffff_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_glass_75_d0e5f5_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_75_d0e5f5_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_glass_85_dfeffc_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_85_dfeffc_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_glass_95_fef1ec_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_95_fef1ec_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_gloss_wave_35_f6a828_500x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_gloss_wave_35_f6a828_500x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_gloss_wave_55_5c9ccc_500x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_gloss_wave_55_5c9ccc_500x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_highlight_hard_20_0972a5_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_hard_20_0972a5_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_highlight_soft_100_eeeeee_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_100_eeeeee_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_highlight_soft_33_003147_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_33_003147_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_highlight_soft_35_222222_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_35_222222_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_highlight_soft_44_444444_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_44_444444_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_highlight_soft_75_ffe45c_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_75_ffe45c_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_highlight_soft_80_eeeeee_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_80_eeeeee_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_inset_hard_100_f5f8f9_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_inset_hard_100_f5f8f9_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_inset_hard_100_fcfdfd_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_inset_hard_100_fcfdfd_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_loop_25_000000_21x21 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_loop_25_000000_21x21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_217bc0_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_217bc0_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_222222_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_222222_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_222222_256x2401 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_222222_256x2401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_228ef1_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_228ef1_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_2e83ff_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_2e83ff_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_469bdd_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_469bdd_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_4b8e0b_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_4b8e0b_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_6da8d5_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_6da8d5_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_a83300_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_a83300_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_cccccc_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_cccccc_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_cd0a0a_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_cd0a0a_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_d8e7f3_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_d8e7f3_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_ef8c08_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_ef8c08_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_f9bd01_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_f9bd01_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_ffd27a_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_ffd27a_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_ffffff_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_ffffff_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_icons_ffffff_256x2401 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_ffffff_256x2401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Grid*/
        ///.ui-jqgrid {position: relative; font-size:11px;}
        ///.ui-jqgrid .ui-jqgrid-view {position: relative;left:0; top: 0; padding: 0;}
        ////* caption*/
        ///.ui-jqgrid .ui-jqgrid-titlebar {padding: .3em .2em .2em .3em; position: relative; border:1px solid silver;}
        ///.ui-jqgrid .ui-jqgrid-title { float: left; margin: .1em 0 .2em; }
        ///.ui-jqgrid .ui-jqgrid-titlebar-close { position: absolute;top: 50%; width: 19px; margin: -15px 0 0 10px; padding: 1px; height:18px;}.ui-jqgrid .ui-jqgrid-titlebar-close span { display:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uiGrid {
            get {
                return ResourceManager.GetString("uiGrid", resourceCulture);
            }
        }
    }
}
