//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralTools.SmsBodyBox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmsBodyBoxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmsBodyBoxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneralTools.SmsBodyBox.SmsBodyBoxResources", typeof(SmsBodyBoxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smsCalculations.js.
        /// </summary>
        internal static string JavaScript_SmsCalculations {
            get {
                return ResourceManager.GetString("JavaScript_SmsCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function calculateSmsCount(txtSmsBodyName, smsInfoCellName, characterTitle, smsTitle) {
        ///	var smsInfoCell = $(&quot;#&quot; + smsInfoCellName)[0];
        ///	var txtSmsBody = $(&quot;#&quot; + txtSmsBodyName)[0];
        ///	var standardSmsLen = 160;
        ///	var standardUdhLen = 7;
        ///
        ///	if (hasUniCodeCharacter(txtSmsBody.value)) {
        ///		standardSmsLen = 70;
        ///		standardUdhLen = 4;
        ///	}
        ///
        ///	var smsLen = replaceString(txtSmsBody.value,&quot;\r\n&quot;,&quot;\n&quot;).length;
        ///	var smsCount = 0
        ///
        ///	if (smsLen &gt; standardSmsLen)
        ///		smsCount = Math.ceil(smsLen / (standardSmsLen - st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string smsCalculations {
            get {
                return ResourceManager.GetString("smsCalculations", resourceCulture);
            }
        }
    }
}
