//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Arad.SMS.Gateway.MagfaSmsSender.MagfaWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TSOAPSoapBinding", Namespace="http://magfa.com/soap/SOAPSmsQueue")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CustomerReturnIncomingFormat))]
    public partial class SoapSmsQueuableImplementationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getMessageStatusesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessageStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRealMessageStatusesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllMessagesWithNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessagesWithNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessageIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback enqueueWithGatewayOperationCompleted;
        
        private System.Threading.SendOrPostCallback enqueueOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SoapSmsQueuableImplementationService() {
            this.Url = global::Arad.SMS.Gateway.MagfaSmsSender.Properties.Settings.Default.MagfaSmsSender_MagfaWebService_SoapSmsQueuableImplementationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getMessageStatusesCompletedEventHandler getMessageStatusesCompleted;
        
        /// <remarks/>
        public event getMessageStatusCompletedEventHandler getMessageStatusCompleted;
        
        /// <remarks/>
        public event getRealMessageStatusesCompletedEventHandler getRealMessageStatusesCompleted;
        
        /// <remarks/>
        public event getAllMessagesWithNumberCompletedEventHandler getAllMessagesWithNumberCompleted;
        
        /// <remarks/>
        public event getMessagesWithNumberCompletedEventHandler getMessagesWithNumberCompleted;
        
        /// <remarks/>
        public event getMessageIdCompletedEventHandler getMessageIdCompleted;
        
        /// <remarks/>
        public event getCreditCompletedEventHandler getCreditCompleted;
        
        /// <remarks/>
        public event getAllMessagesCompletedEventHandler getAllMessagesCompleted;
        
        /// <remarks/>
        public event getMessagesCompletedEventHandler getMessagesCompleted;
        
        /// <remarks/>
        public event enqueueWithGatewayCompletedEventHandler enqueueWithGatewayCompleted;
        
        /// <remarks/>
        public event enqueueCompletedEventHandler enqueueCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMessageStatusesReturn")]
        public int[] getMessageStatuses(long[] messagesId) {
            object[] results = this.Invoke("getMessageStatuses", new object[] {
                        messagesId});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void getMessageStatusesAsync(long[] messagesId) {
            this.getMessageStatusesAsync(messagesId, null);
        }
        
        /// <remarks/>
        public void getMessageStatusesAsync(long[] messagesId, object userState) {
            if ((this.getMessageStatusesOperationCompleted == null)) {
                this.getMessageStatusesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageStatusesOperationCompleted);
            }
            this.InvokeAsync("getMessageStatuses", new object[] {
                        messagesId}, this.getMessageStatusesOperationCompleted, userState);
        }
        
        private void OngetMessageStatusesOperationCompleted(object arg) {
            if ((this.getMessageStatusesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageStatusesCompleted(this, new getMessageStatusesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMessageStatusReturn")]
        public int getMessageStatus(long messageId) {
            object[] results = this.Invoke("getMessageStatus", new object[] {
                        messageId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getMessageStatusAsync(long messageId) {
            this.getMessageStatusAsync(messageId, null);
        }
        
        /// <remarks/>
        public void getMessageStatusAsync(long messageId, object userState) {
            if ((this.getMessageStatusOperationCompleted == null)) {
                this.getMessageStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageStatusOperationCompleted);
            }
            this.InvokeAsync("getMessageStatus", new object[] {
                        messageId}, this.getMessageStatusOperationCompleted, userState);
        }
        
        private void OngetMessageStatusOperationCompleted(object arg) {
            if ((this.getMessageStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageStatusCompleted(this, new getMessageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRealMessageStatusesReturn")]
        public int[] getRealMessageStatuses(long[] messagesId) {
            object[] results = this.Invoke("getRealMessageStatuses", new object[] {
                        messagesId});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void getRealMessageStatusesAsync(long[] messagesId) {
            this.getRealMessageStatusesAsync(messagesId, null);
        }
        
        /// <remarks/>
        public void getRealMessageStatusesAsync(long[] messagesId, object userState) {
            if ((this.getRealMessageStatusesOperationCompleted == null)) {
                this.getRealMessageStatusesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRealMessageStatusesOperationCompleted);
            }
            this.InvokeAsync("getRealMessageStatuses", new object[] {
                        messagesId}, this.getRealMessageStatusesOperationCompleted, userState);
        }
        
        private void OngetRealMessageStatusesOperationCompleted(object arg) {
            if ((this.getRealMessageStatusesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRealMessageStatusesCompleted(this, new getRealMessageStatusesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllMessagesWithNumberReturn")]
        public object[] getAllMessagesWithNumber(string domain, int numberOfMessages, string destNumber) {
            object[] results = this.Invoke("getAllMessagesWithNumber", new object[] {
                        domain,
                        numberOfMessages,
                        destNumber});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllMessagesWithNumberAsync(string domain, int numberOfMessages, string destNumber) {
            this.getAllMessagesWithNumberAsync(domain, numberOfMessages, destNumber, null);
        }
        
        /// <remarks/>
        public void getAllMessagesWithNumberAsync(string domain, int numberOfMessages, string destNumber, object userState) {
            if ((this.getAllMessagesWithNumberOperationCompleted == null)) {
                this.getAllMessagesWithNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllMessagesWithNumberOperationCompleted);
            }
            this.InvokeAsync("getAllMessagesWithNumber", new object[] {
                        domain,
                        numberOfMessages,
                        destNumber}, this.getAllMessagesWithNumberOperationCompleted, userState);
        }
        
        private void OngetAllMessagesWithNumberOperationCompleted(object arg) {
            if ((this.getAllMessagesWithNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllMessagesWithNumberCompleted(this, new getAllMessagesWithNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMessagesWithNumberReturn")]
        public object[] getMessagesWithNumber(string domain, int numberOfMessages, string destNumber) {
            object[] results = this.Invoke("getMessagesWithNumber", new object[] {
                        domain,
                        numberOfMessages,
                        destNumber});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getMessagesWithNumberAsync(string domain, int numberOfMessages, string destNumber) {
            this.getMessagesWithNumberAsync(domain, numberOfMessages, destNumber, null);
        }
        
        /// <remarks/>
        public void getMessagesWithNumberAsync(string domain, int numberOfMessages, string destNumber, object userState) {
            if ((this.getMessagesWithNumberOperationCompleted == null)) {
                this.getMessagesWithNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessagesWithNumberOperationCompleted);
            }
            this.InvokeAsync("getMessagesWithNumber", new object[] {
                        domain,
                        numberOfMessages,
                        destNumber}, this.getMessagesWithNumberOperationCompleted, userState);
        }
        
        private void OngetMessagesWithNumberOperationCompleted(object arg) {
            if ((this.getMessagesWithNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessagesWithNumberCompleted(this, new getMessagesWithNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMessageIdReturn")]
        public long getMessageId(string domain, long checkingMessageId) {
            object[] results = this.Invoke("getMessageId", new object[] {
                        domain,
                        checkingMessageId});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void getMessageIdAsync(string domain, long checkingMessageId) {
            this.getMessageIdAsync(domain, checkingMessageId, null);
        }
        
        /// <remarks/>
        public void getMessageIdAsync(string domain, long checkingMessageId, object userState) {
            if ((this.getMessageIdOperationCompleted == null)) {
                this.getMessageIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageIdOperationCompleted);
            }
            this.InvokeAsync("getMessageId", new object[] {
                        domain,
                        checkingMessageId}, this.getMessageIdOperationCompleted, userState);
        }
        
        private void OngetMessageIdOperationCompleted(object arg) {
            if ((this.getMessageIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageIdCompleted(this, new getMessageIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("getCreditReturn")]
        public float getCredit(string domain) {
            object[] results = this.Invoke("getCredit", new object[] {
                        domain});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void getCreditAsync(string domain) {
            this.getCreditAsync(domain, null);
        }
        
        /// <remarks/>
        public void getCreditAsync(string domain, object userState) {
            if ((this.getCreditOperationCompleted == null)) {
                this.getCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCreditOperationCompleted);
            }
            this.InvokeAsync("getCredit", new object[] {
                        domain}, this.getCreditOperationCompleted, userState);
        }
        
        private void OngetCreditOperationCompleted(object arg) {
            if ((this.getCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCreditCompleted(this, new getCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllMessagesReturn")]
        public object[] getAllMessages(string domain, int numberOfMessages) {
            object[] results = this.Invoke("getAllMessages", new object[] {
                        domain,
                        numberOfMessages});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllMessagesAsync(string domain, int numberOfMessages) {
            this.getAllMessagesAsync(domain, numberOfMessages, null);
        }
        
        /// <remarks/>
        public void getAllMessagesAsync(string domain, int numberOfMessages, object userState) {
            if ((this.getAllMessagesOperationCompleted == null)) {
                this.getAllMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllMessagesOperationCompleted);
            }
            this.InvokeAsync("getAllMessages", new object[] {
                        domain,
                        numberOfMessages}, this.getAllMessagesOperationCompleted, userState);
        }
        
        private void OngetAllMessagesOperationCompleted(object arg) {
            if ((this.getAllMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllMessagesCompleted(this, new getAllMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMessagesReturn")]
        public object[] getMessages(string domain, int numberOfMessages) {
            object[] results = this.Invoke("getMessages", new object[] {
                        domain,
                        numberOfMessages});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getMessagesAsync(string domain, int numberOfMessages) {
            this.getMessagesAsync(domain, numberOfMessages, null);
        }
        
        /// <remarks/>
        public void getMessagesAsync(string domain, int numberOfMessages, object userState) {
            if ((this.getMessagesOperationCompleted == null)) {
                this.getMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessagesOperationCompleted);
            }
            this.InvokeAsync("getMessages", new object[] {
                        domain,
                        numberOfMessages}, this.getMessagesOperationCompleted, userState);
        }
        
        private void OngetMessagesOperationCompleted(object arg) {
            if ((this.getMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessagesCompleted(this, new getMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("enqueueWithGatewayReturn")]
        public long[] enqueueWithGateway(string domain, string[] messageBodies, string[] recipientNumbers, string[] senderNumbers, int[] encodings, string[] udhs, int[] messageClasses, int[] priorities, long[] checkingMessageIds, string gateway) {
            object[] results = this.Invoke("enqueueWithGateway", new object[] {
                        domain,
                        messageBodies,
                        recipientNumbers,
                        senderNumbers,
                        encodings,
                        udhs,
                        messageClasses,
                        priorities,
                        checkingMessageIds,
                        gateway});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public void enqueueWithGatewayAsync(string domain, string[] messageBodies, string[] recipientNumbers, string[] senderNumbers, int[] encodings, string[] udhs, int[] messageClasses, int[] priorities, long[] checkingMessageIds, string gateway) {
            this.enqueueWithGatewayAsync(domain, messageBodies, recipientNumbers, senderNumbers, encodings, udhs, messageClasses, priorities, checkingMessageIds, gateway, null);
        }
        
        /// <remarks/>
        public void enqueueWithGatewayAsync(string domain, string[] messageBodies, string[] recipientNumbers, string[] senderNumbers, int[] encodings, string[] udhs, int[] messageClasses, int[] priorities, long[] checkingMessageIds, string gateway, object userState) {
            if ((this.enqueueWithGatewayOperationCompleted == null)) {
                this.enqueueWithGatewayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenqueueWithGatewayOperationCompleted);
            }
            this.InvokeAsync("enqueueWithGateway", new object[] {
                        domain,
                        messageBodies,
                        recipientNumbers,
                        senderNumbers,
                        encodings,
                        udhs,
                        messageClasses,
                        priorities,
                        checkingMessageIds,
                        gateway}, this.enqueueWithGatewayOperationCompleted, userState);
        }
        
        private void OnenqueueWithGatewayOperationCompleted(object arg) {
            if ((this.enqueueWithGatewayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enqueueWithGatewayCompleted(this, new enqueueWithGatewayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://magfa.com/soap/SOAPSmsQueue", ResponseNamespace="http://magfa.com/soap/SOAPSmsQueue")]
        [return: System.Xml.Serialization.SoapElementAttribute("enqueueReturn")]
        public long[] enqueue(string domain, string[] messageBodies, string[] recipientNumbers, string[] senderNumbers, int[] encodings, string[] udhs, int[] messageClasses, int[] priorities, long[] checkingMessageIds) {
            object[] results = this.Invoke("enqueue", new object[] {
                        domain,
                        messageBodies,
                        recipientNumbers,
                        senderNumbers,
                        encodings,
                        udhs,
                        messageClasses,
                        priorities,
                        checkingMessageIds});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public void enqueueAsync(string domain, string[] messageBodies, string[] recipientNumbers, string[] senderNumbers, int[] encodings, string[] udhs, int[] messageClasses, int[] priorities, long[] checkingMessageIds) {
            this.enqueueAsync(domain, messageBodies, recipientNumbers, senderNumbers, encodings, udhs, messageClasses, priorities, checkingMessageIds, null);
        }
        
        /// <remarks/>
        public void enqueueAsync(string domain, string[] messageBodies, string[] recipientNumbers, string[] senderNumbers, int[] encodings, string[] udhs, int[] messageClasses, int[] priorities, long[] checkingMessageIds, object userState) {
            if ((this.enqueueOperationCompleted == null)) {
                this.enqueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenqueueOperationCompleted);
            }
            this.InvokeAsync("enqueue", new object[] {
                        domain,
                        messageBodies,
                        recipientNumbers,
                        senderNumbers,
                        encodings,
                        udhs,
                        messageClasses,
                        priorities,
                        checkingMessageIds}, this.enqueueOperationCompleted, userState);
        }
        
        private void OnenqueueOperationCompleted(object arg) {
            if ((this.enqueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enqueueCompleted(this, new enqueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(DatedCustomerReturnIncomingFormat))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SOAPSmsQueue")]
    public partial class CustomerReturnIncomingFormat {
        
        private string bodyField;
        
        private string errorResultField;
        
        private string recipientNumberField;
        
        private string senderNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorResult {
            get {
                return this.errorResultField;
            }
            set {
                this.errorResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recipientNumber {
            get {
                return this.recipientNumberField;
            }
            set {
                this.recipientNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string senderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                this.senderNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SOAPSmsQueue")]
    public partial class DatedCustomerReturnIncomingFormat : CustomerReturnIncomingFormat {
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getMessageStatusesCompletedEventHandler(object sender, getMessageStatusesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageStatusesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageStatusesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getMessageStatusCompletedEventHandler(object sender, getMessageStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getRealMessageStatusesCompletedEventHandler(object sender, getRealMessageStatusesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRealMessageStatusesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRealMessageStatusesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getAllMessagesWithNumberCompletedEventHandler(object sender, getAllMessagesWithNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllMessagesWithNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllMessagesWithNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getMessagesWithNumberCompletedEventHandler(object sender, getMessagesWithNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessagesWithNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessagesWithNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getMessageIdCompletedEventHandler(object sender, getMessageIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getCreditCompletedEventHandler(object sender, getCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getAllMessagesCompletedEventHandler(object sender, getAllMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getMessagesCompletedEventHandler(object sender, getMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void enqueueWithGatewayCompletedEventHandler(object sender, enqueueWithGatewayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enqueueWithGatewayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enqueueWithGatewayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void enqueueCompletedEventHandler(object sender, enqueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enqueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enqueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591