//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralTools.SearchBox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SearchBoxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchBoxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneralTools.SearchBox.SearchBoxResources", typeof(SearchBoxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to styles_min.css.
        /// </summary>
        internal static string Css_Styles {
            get {
                return ResourceManager.GetString("Css_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap indicator {
            get {
                object obj = ResourceManager.GetObject("indicator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jquery_Autocomplete_min.js.
        /// </summary>
        internal static string JavaScript_Jquery_Autocomplete {
            get {
                return ResourceManager.GetString("JavaScript_Jquery_Autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jQuery.autocomplete=function(a,b){function L(a){var b=a.offsetLeft||0;var c=a.offsetTop||0;while(a=a.offsetParent){b+=a.offsetLeft;c+=a.offsetTop}return{x:b,y:c}}function K(a,c){if(!c||!a||!b.cacheLength)return;if(!j.length||j.length&gt;b.cacheLength){n();j.length++}else if(!j[a]){j.length++}j.data[a]=c}function J(a,c){if(c)d.removeClass(b.loadingClass);var e=c?c.length:0;var f=null;for(var g=0;g&lt;e;g++){var h=c[g];if(h[0].toLowerCase()==a.toLowerCase()){f=document.createElement(&quot;li&quot;);if(b.formatItem){f.innerHT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_Autocomplete_min {
            get {
                return ResourceManager.GetString("jquery_Autocomplete_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ac_results{padding:0px;border:1px solid WindowFrame;background-color:Window;overflow:hidden}.ac_results ul{width:100%;list-style-position:outside;list-style:none;padding:0;margin:0}.ac_results iframe{display:none;display:block;position:absolute;top:0;left:0;z-index:-1;filter:mask();width:3000px;height:3000px}.ac_results li{margin:0px;padding:2px 5px;cursor:pointer;display:block;width:100%;font:menu;font-size:12px;overflow:hidden}.ac_loading{background:Window url(&lt;%=WebResource(&quot;GeneralTools.SearchBox.Image [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styles_min {
            get {
                return ResourceManager.GetString("styles_min", resourceCulture);
            }
        }
    }
}
