//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arad.SMS.Gateway.Web.UI.Settings {
    
    
    public partial class AdminSetting {
        
        /// <summary>
        /// txtVasRegisterSmsText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtVasRegisterSmsText;
        
        /// <summary>
        /// txtSendSmsAlertMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtSendSmsAlertMessage;
        
        /// <summary>
        /// txtRegisterFishSmsText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtRegisterFishSmsText;
        
        /// <summary>
        /// txtOnlinePaymentSmsText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtOnlinePaymentSmsText;
        
        /// <summary>
        /// txtLoginSmsText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtLoginSmsText;
        
        /// <summary>
        /// txtLowCreditSmsText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtLowCreditSmsText;
        
        /// <summary>
        /// txtRegisterUserSmsText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtRegisterUserSmsText;
        
        /// <summary>
        /// txtUserAccountSmsText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtUserAccountSmsText;
        
        /// <summary>
        /// txtUserExpireSmsText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtUserExpireSmsText;
        
        /// <summary>
        /// txtRetrievePasswordSmsText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeneralTools.SmsBodyBox.SmsBodyBox txtRetrievePasswordSmsText;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
