//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Arad.SMS.Gateway.GetSmsDelivery.AsanakWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CompositeSmsGatewayServiceSoapBinding", Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseResult))]
    public partial class CompositeSmsGatewayService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getReportByMsgIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReceivedMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendSmsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CompositeSmsGatewayService() {
            this.Url = global::Arad.SMS.Gateway.GetSmsDelivery.Properties.Settings.Default.GetSmsDelivery_AsanakWebService_CompositeSmsGatewayService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getReportByMsgIdCompletedEventHandler getReportByMsgIdCompleted;
        
        /// <remarks/>
        public event getReceivedMsgCompletedEventHandler getReceivedMsgCompleted;
        
        /// <remarks/>
        public event getUserCreditCompletedEventHandler getUserCreditCompleted;
        
        /// <remarks/>
        public event sendSmsCompletedEventHandler sendSmsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", ResponseNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public getReportByMsgIdResult getReportByMsgId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] userCredential userCredential, [System.Xml.Serialization.XmlElementAttribute("msgIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long[] msgIds) {
            object[] results = this.Invoke("getReportByMsgId", new object[] {
                        userCredential,
                        msgIds});
            return ((getReportByMsgIdResult)(results[0]));
        }
        
        /// <remarks/>
        public void getReportByMsgIdAsync(userCredential userCredential, long[] msgIds) {
            this.getReportByMsgIdAsync(userCredential, msgIds, null);
        }
        
        /// <remarks/>
        public void getReportByMsgIdAsync(userCredential userCredential, long[] msgIds, object userState) {
            if ((this.getReportByMsgIdOperationCompleted == null)) {
                this.getReportByMsgIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReportByMsgIdOperationCompleted);
            }
            this.InvokeAsync("getReportByMsgId", new object[] {
                        userCredential,
                        msgIds}, this.getReportByMsgIdOperationCompleted, userState);
        }
        
        private void OngetReportByMsgIdOperationCompleted(object arg) {
            if ((this.getReportByMsgIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReportByMsgIdCompleted(this, new getReportByMsgIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", ResponseNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public getReceivedMsgResult getReceivedMsg([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] userCredential userCredential, [System.Xml.Serialization.XmlElementAttribute("destAddresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] destAddresses, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long fromTime, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int maxReturnedMsg) {
            object[] results = this.Invoke("getReceivedMsg", new object[] {
                        userCredential,
                        destAddresses,
                        fromTime,
                        maxReturnedMsg});
            return ((getReceivedMsgResult)(results[0]));
        }
        
        /// <remarks/>
        public void getReceivedMsgAsync(userCredential userCredential, string[] destAddresses, long fromTime, int maxReturnedMsg) {
            this.getReceivedMsgAsync(userCredential, destAddresses, fromTime, maxReturnedMsg, null);
        }
        
        /// <remarks/>
        public void getReceivedMsgAsync(userCredential userCredential, string[] destAddresses, long fromTime, int maxReturnedMsg, object userState) {
            if ((this.getReceivedMsgOperationCompleted == null)) {
                this.getReceivedMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReceivedMsgOperationCompleted);
            }
            this.InvokeAsync("getReceivedMsg", new object[] {
                        userCredential,
                        destAddresses,
                        fromTime,
                        maxReturnedMsg}, this.getReceivedMsgOperationCompleted, userState);
        }
        
        private void OngetReceivedMsgOperationCompleted(object arg) {
            if ((this.getReceivedMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReceivedMsgCompleted(this, new getReceivedMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", ResponseNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userCreditResult getUserCredit([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] userCredential userCredential) {
            object[] results = this.Invoke("getUserCredit", new object[] {
                        userCredential});
            return ((userCreditResult)(results[0]));
        }
        
        /// <remarks/>
        public void getUserCreditAsync(userCredential userCredential) {
            this.getUserCreditAsync(userCredential, null);
        }
        
        /// <remarks/>
        public void getUserCreditAsync(userCredential userCredential, object userState) {
            if ((this.getUserCreditOperationCompleted == null)) {
                this.getUserCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserCreditOperationCompleted);
            }
            this.InvokeAsync("getUserCredit", new object[] {
                        userCredential}, this.getUserCreditOperationCompleted, userState);
        }
        
        private void OngetUserCreditOperationCompleted(object arg) {
            if ((this.getUserCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserCreditCompleted(this, new getUserCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", ResponseNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sendSmsResult sendSms([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] userCredential userCredential, [System.Xml.Serialization.XmlElementAttribute("srcAddresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] srcAddresses, [System.Xml.Serialization.XmlElementAttribute("destAddresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] destAddresses, [System.Xml.Serialization.XmlElementAttribute("msgBody", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] msgBody, [System.Xml.Serialization.XmlElementAttribute("msgEncoding", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int[] msgEncoding) {
            object[] results = this.Invoke("sendSms", new object[] {
                        userCredential,
                        srcAddresses,
                        destAddresses,
                        msgBody,
                        msgEncoding});
            return ((sendSmsResult)(results[0]));
        }
        
        /// <remarks/>
        public void sendSmsAsync(userCredential userCredential, string[] srcAddresses, string[] destAddresses, string[] msgBody, int[] msgEncoding) {
            this.sendSmsAsync(userCredential, srcAddresses, destAddresses, msgBody, msgEncoding, null);
        }
        
        /// <remarks/>
        public void sendSmsAsync(userCredential userCredential, string[] srcAddresses, string[] destAddresses, string[] msgBody, int[] msgEncoding, object userState) {
            if ((this.sendSmsOperationCompleted == null)) {
                this.sendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSmsOperationCompleted);
            }
            this.InvokeAsync("sendSms", new object[] {
                        userCredential,
                        srcAddresses,
                        destAddresses,
                        msgBody,
                        msgEncoding}, this.sendSmsOperationCompleted, userState);
        }
        
        private void OnsendSmsOperationCompleted(object arg) {
            if ((this.sendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSmsCompleted(this, new sendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class userCredential {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class receivedMsg {
        
        private string bodyField;
        
        private string destinationField;
        
        private int encodingField;
        
        private long idField;
        
        private int partCountField;
        
        private long receivedTimeField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int partCount {
            get {
                return this.partCountField;
            }
            set {
                this.partCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long receivedTime {
            get {
                return this.receivedTimeField;
            }
            set {
                this.receivedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class reportItem {
        
        private long deliveryDateField;
        
        private string destinationField;
        
        private long msgIdField;
        
        private string sourceField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long deliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sendSmsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(userCreditResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getReceivedMsgResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getReportByMsgIdResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public abstract partial class baseResult {
        
        private string errorMsgField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class sendSmsResult : baseResult {
        
        private System.Nullable<long>[] msgIdArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("msgIdArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<long>[] msgIdArray {
            get {
                return this.msgIdArrayField;
            }
            set {
                this.msgIdArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class userCreditResult : baseResult {
        
        private int creditField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class getReceivedMsgResult : baseResult {
        
        private receivedMsg[] receivedMegsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("receivedMegs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public receivedMsg[] receivedMegs {
            get {
                return this.receivedMegsField;
            }
            set {
                this.receivedMegsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class getReportByMsgIdResult : baseResult {
        
        private reportItem[] reportItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public reportItem[] reportItems {
            get {
                return this.reportItemsField;
            }
            set {
                this.reportItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getReportByMsgIdCompletedEventHandler(object sender, getReportByMsgIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReportByMsgIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReportByMsgIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getReportByMsgIdResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getReportByMsgIdResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getReceivedMsgCompletedEventHandler(object sender, getReceivedMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReceivedMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReceivedMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getReceivedMsgResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getReceivedMsgResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getUserCreditCompletedEventHandler(object sender, getUserCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public userCreditResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((userCreditResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sendSmsCompletedEventHandler(object sender, sendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sendSmsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sendSmsResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591